server:
  backPort: 1016
  frontPort: 8080
  host: localhost
database:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: aliyun
  indexdatabase: duibi
  rundatabase: ceshi2
  username: root
  password: 123456
  charset: utf8mb4
  loc: Asia/Shanghai